config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "homes#top"
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  get 'movies/search'
  resources :movies, only: [:show] do
    resource :watcheds, only: [:new, :create, :edit, :update, :destroy]
    resource :checks, only: [:create, :update, :destroy]
  end

  get 'genres/:id' => 'genres#show', as: 'genre'
  get 'people/:id' => 'people#show', as: 'person'

  

  namespace :admins do
    root to: "homes#top"
    get 'homes/about'
    resources :users, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  include ActiveModel::Model

	include HTTParty

  # default_options.update(verify: false) # disable SSL verification(必要に応じて)
  default_params api_key: ENV['TMDb_API_KEY'], language: 'en-US' #共通パラメタ
  format :json

  # キーワードによる検索機能
  # https://developers.themoviedb.org/3/search/search-keywordsを参照
  def self.search term
    base_uri 'https://api.themoviedb.org/3/search/movie'
    get("", query: { query: term }) # {}の中身はパラメタ
  end

  # 指定の映画の詳細情報を取得
  # https://developers.themoviedb.org/3/movies/get-movie-detailsを参照
  def self.details id
    base_uri "https://api.themoviedb.org/3/movie/#{id}"
    get("", query: { } ) #パラメタなし
  end

  # 指定のクレジットを取得
  # https://developers.themoviedb.org/3/movies/get-movie-creditsを参照
  def self.credits id
    base_uri "https://api.themoviedb.org/3/movie/#{id}/credits"
    get("", query: { } ) #パラメタなし
  end

  # 指定のクレジットの詳細情報を取得
  # https://developers.themoviedb.org/3/movies/get-credit-detailsを参照
  def self.credit_details id
    base_uri "https://api.themoviedb.org/3/credit/#{id}"
    get("", query: { } ) #パラメタなし
  end

  # 指定の映画の予告編を取得
  # https://developers.themoviedb.org/3/genres/get-movie-listを参照
  def self.videos id
    base_uri "https://api.themoviedb.org/3/movie/#{id}/videos"
    get("", query: { } ) #パラメタなし
  end

  # 指定の映画のジャンルを取得
  # https://developers.themoviedb.org/3/genres/get-movie-listを参照
  def self.genres
    base_uri "https://api.themoviedb.org/3/genre/movie/list"
    get("", query: { } ) #パラメタなし
  end

  # トレンドの映画一覧を取得
  # https://developers.themoviedb.org/3/trending/get-trendingを参照
  def self.trendings
    base_uri "https://api.themoviedb.org/3/trending/movie/week"
    get("", query: { } ) #パラメタなし
  end
end

app/models/person.rb
class Person < ApplicationRecord
	include ActiveModel::Model 
	include HTTParty

	# default_options.update(verify: false) # disable SSL verification(必要に応じて)
	default_params api_key: ENV['TMDb_API_KEY'], language: 'en-US' #共通パラメタ
	format :json

	# 指定のパーソンの詳細を取得
	# https://developers.themoviedb.org/3/people/get-person-detailsを参照
	def self.details id
		base_uri "https://api.themoviedb.org/3/person/#{id}"
		get("", query: { } ) #パラメタなし
	end

	# 指定のパーソンの映画作品全てを取得
	# https://developers.themoviedb.org/3/people/get-person-movie-creditsを参照
	def self.movie_credits id
		base_uri "https://api.themoviedb.org/3/person/#{id}/movie_credits"
		get("", query: { } ) #パラメタなし
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :watcheds
  has_many :checks
end

app/models/watched.rb
class Watched < ApplicationRecord
  belongs_to :user
  enum rate: {AllTimeBest: 0, LOVE: 1, LIKE: 2, OK: 3, DISLIKE: 4}
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def create
    check = current_user.checks.new
    check.tmdb_movie_id = params[:movie_id]
    check.save!
    redirect_to movie_path(params[:movie_id])
  end

  def update
    check = current_user.checks.find_by(tmdb_movie_id: params[:movie_id])
    check.update(prepare: true)
    redirect_to movie_path(params[:movie_id])
  end

  def destroy
    check = current_user.checks.find_by(tmdb_movie_id: params[:movie_id])
    check.destroy
    redirect_to movie_path(params[:movie_id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @trend_movies = Movie.trendings["results"]
    @watcheds = current_user.watcheds
    @checks = current_user.checks
  end

  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def search
    @search_term = params[:looking_for]
    @movie_results = Movie.search(@search_term)["results"]
    @watcheds = current_user.watcheds
    @checks = current_user.checks
  end

  def show
    @movie_info = Movie.details(params[:id])
    @videos = Movie.videos(params[:id])['results']
    @crews = Movie.credits(params[:id])['crew']
    @directors = []
    @writers = []
    @screenplays = []
    @crews.each do |crew|
      if crew['job'] == "Director"
        @directors << crew
      elsif crew['job'] == "Writer"
        @writers << crew
      elsif crew['job'] == "Screenplay"
        @screenplays << crew
      end
    end
    @casts = Movie.credits(params[:id])['cast']
    @watched = current_user.watcheds.find_by(tmdb_movie_id: @movie_info["id"]) || Watched.new
    @check = current_user.checks.find_by(tmdb_movie_id: @movie_info["id"]) || Check.new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  def show
    @user = User.find(params[:id])
    @watcheds = @user.watcheds
    @watched_movie_ids = []
    @watcheds.each do |watched|
      @watched_movie_ids << watched.tmdb_movie_id
    end
    @checks = @user.checks
    @check_movie_ids = []
    @checks.each do |check|
      @check_movie_ids << check.tmdb_movie_id
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
		if	@user.update(user_params)
			flash[:notice] = "successfully"
			redirect_to user_path(current_user.id)
		else
			flash[:notice] = "error"
			render :edit
		end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watcheds_helper.rb
module WatchedsHelper
end

app/views/movies/search.html.erb
<div class="container">
    <p class="h2">SEARCH RESULTS FOR "<%= @search_term %>"</p>
    <% if @movie_results.blank? %>
        <p>Not Found.</p>
    <% else %>
        <% @movie_results.each do |movie| %>
        <div class="inline">
            <div>
                <%= link_to image_tag("https://image.tmdb.org/t/p/w200#{movie["poster_path"]}", alt: "poster", class: "img-responsive"), movie_path(movie["id"]) %>
            </div>
            <div>
                <p class="center"><%= link_to movie['title'], movie_path(movie["id"]) %></p>
            </div>
        </div>
        <% end %>
    <% end %>
</div>

app/views/movies/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <%= image_tag "https://image.tmdb.org/t/p/w200#{@movie_info["poster_path"]}", size: "400x800", alt: "poster", class: "img-responsive" %>
            <div class="center">
                <% if @watched.new_record? %>
                    <%= link_to "WATCHED", new_movie_watcheds_path(@movie_info["id"]), remote: true, class: "btn btn-lg" %>
                    <%# Watched createのモーダルウィンドウ %>
                    <div class="modal fade" id="watched-create-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <%= form_with model: @watched, local: true, url:movie_watcheds_path(params[:id], method: :post) do |f| %>
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group ">
                                            <%= f.label :rate, class: "form-control-label" %>
                                            <%= f.radio_button :rate, :AllTimeBest %>
                                            <%= f.label(:rate, value: "AllTimeBest") %>
                                            <%= f.radio_button :rate, :LOVE %>
                                            <%= f.label(:rate, value: "LOVE") %>
                                            <%= f.radio_button :rate, :LIKE %>
                                            <%= f.label(:rate, value: "LIKE") %>
                                            <%= f.radio_button :rate, :OK %>
                                            <%= f.label(:rate, value: "OK") %>
                                            <%= f.radio_button :rate, :DISLIKE %>
                                            <%= f.label(:rate, value: "DISLIKE") %>
                                        </div>
                                        <div class="form-group field">
                                            <%= f.label :review, class: "form-control-abel" %>
                                            <%= f.text_field :review, class: "form-control" %>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <%= f.submit "WATCHED!", class:"btn" %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <%# ここまで %>
                <% else %>
                    <%= link_to @watched.rate, edit_movie_watcheds_path(@movie_info["id"]), remote: true, class: "btn btn-lg btn-warning" %>
                    <%# Watched updateのモーダルウィンドウ %>
                    <div class="modal fade" id="watched-update-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <%= form_with model: @watched, local: true, url:movie_watcheds_path(params[:id], method: :patch) do |f| %>
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group ">
                                            <%= f.label :rate, class: "form-control-label" %>
                                            <%= f.radio_button :rate, :AllTimeBest %>
                                            <%= f.label(:rate, value: "AllTimeBest") %>
                                            <%= f.radio_button :rate, :LOVE %>
                                            <%= f.label(:rate, value: "LOVE") %>
                                            <%= f.radio_button :rate, :LIKE %>
                                            <%= f.label(:rate, value: "LIKE") %>
                                            <%= f.radio_button :rate, :OK %>
                                            <%= f.label(:rate, value: "OK") %>
                                            <%= f.radio_button :rate, :DISLIKE %>
                                            <%= f.label(:rate, value: "DISLIKE") %>
                                        </div>
                                        <div class="form-group field">
                                            <%= f.label :review, class: "form-control-abel" %>
                                            <%= f.text_field :review, class: "form-control" %>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <%= f.submit "WATCHED!", class:"btn" %>
                                        <%= link_to  "DELETE!", movie_watcheds_path(params[:id]), method: :delete, data: {confirm: 'Are you sure?'}%>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <%# ここまで %>
                <% end %>
            </div>
            <div class="center">
                <% if @check.new_record? %>
                    <%= link_to "CHECK", movie_checks_path(@movie_info["id"]), method: :post, class: "btn btn-lg" %>
                <% elsif @check.prepare.blank? %>
                    <%= link_to "CHECK!", movie_checks_path(@movie_info["id"]), method: :patch, class: "btn btn-lg btn-warning" %>
                <% else %>
                    <%= link_to "PREPARATION!", movie_checks_path(@movie_info["id"]), method: :delete, class: "btn btn-lg btn-danger" %>
                <% end %>
            </div>
            <div>
                <p class="h4"><strong>RELEASE：</strong><%= @movie_info['release_date'] %></p>
                <p class="h4"><strong>RUNNING TIME：</strong><%= @movie_info['runtime'] %>min</p>
                <p class="h4">
                    <strong>GENRE：</strong>
                    <% @movie_info['genres'].each do |genre| %>
                        <span><%= genre['name'] %></span>
                    <% end %>
                </p>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="h1"><strong><%= @movie_info['title'] %></div>
            <div>
                <div class="h3"><strong>DIRECTOR</strong></div>
                <% @directors.each do |director| %>
                    <% if director == @directors.last %>
                        <span class="h4"><%= link_to director['name'], person_path(director['id']) %></span>
                    <% else %>
                        <span class="h4"><%= link_to director['name'], person_path(director['id']) %>,</span>
                    <% end %>
                <% end %>
            </div>
            <div>
                <div class="h3"><strong>SCREENPLAY</strong></div>
                <% @screenplays.each do |screenplay| %>
                    <% if screenplay == @screenplays.last %>
                        <span class="h4"><%= link_to screenplay['name'], person_path(screenplay['id']) %></span>
                    <% else %>
                        <span class="h4"><%= link_to screenplay['name'], person_path(screenplay['id']) %>,</span>
                    <% end %>
                <% end %>
                <% @writers.each do |writer| %>
                    <% if writer == @writers.last %>
                        <span class="h4"><%= link_to writer['name'], person_path(writer['id']) %></span>
                    <% else %>
                        <span class="h4"><%= link_to writer['name'], person_path(writer['id']) %>,</span>
                    <% end %>
                <% end %>
            </div>
            <div>
                <div class="h3"><strong>CAST</strong></div>
                <% @casts.each do |cast| %>
                    <% if cast == @casts.last %>
                        <span class="h4"><%= link_to cast['name'], person_path(cast['id']) %></span>
                    <% else %>
                        <span class="h4"><%= link_to cast['name'], person_path(cast['id']) %>,</span>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <% if @movie_info['overview'].present? %>
        <p class="h4"><strong>OVERVIEW：</strong><%= @movie_info['overview'] %></p>
    <% end %>
    <% if @videos.present? %>
        <p class="h4"><strong>VIDEOS</strong></p>
        <iframe width="1120" height="630" src="https://www.youtube.com/embed/<%= @videos.first["key"] %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
</div>