config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "homes#top"
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  get 'movies/search'
  resources :movies, only: [:show] do
    resource :watcheds, only: [:new, :create, :edit, :update, :destroy]
    resource :checks, only: [:create, :update, :destroy]
  end

  get 'genres/:id' => 'genres#show', as: 'genre'
  get 'people/:id' => 'people#show', as: 'person'

  

  namespace :admins do
    root to: "homes#top"
    get 'homes/about'
    resources :users, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :watcheds
  has_many :checks
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  def show
    @user = User.find(params[:id])
    @watcheds = @user.watcheds
    @watched_movie_ids = []
    @watcheds.each do |watched|
      @watched_movie_ids << watched.tmdb_movie_id
    end
    @checks = @user.checks
    @check_movie_ids = []
    @checks.each do |check|
      @check_movie_ids << check.tmdb_movie_id
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
		if	@user.update(user_params)
			flash[:notice] = "successfully"
			redirect_to user_path(current_user.id)
		else
			flash[:notice] = "error"
			render :edit
		end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2>EDIT</h2>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>
    <div>
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <div>
      <%= f.submit "UPDATE" %>
    </div>
  <% end %>
  <%= link_to "Back", user_path(current_user.id) %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div>
        <p><strong>NAME</strong></p>
        <p><%= @user.name %></p>
    </div>
    <div>
        <p><strong>E-MAIL</strong></p>
        <p><%= @user.email %></p>
    </div>
    <% if @user.id = current_user.id %>
        <div>
            <%= link_to "EDIT INFOMATION", edit_user_path(current_user.id) %><br>
            <%= link_to 'CLOSE ACCOUNT?', user_path(current_user.id), method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>
    <% end %>
    <div>
        <div>
            <p class="h2">WATCHED</p>
            <% @watched_movie_ids.each do |id| %>
                <div class="inline">
                    <% movie_info = Movie.details(id) %>
                    <%= link_to image_tag("https://image.tmdb.org/t/p/w200#{movie_info["poster_path"]}", alt: "poster", class: "img-responsive"), movie_path(id) %>
                    <p class="center"><%= link_to movie_info["title"], movie_path(id) %></p>
                    <p><%= @watcheds.find_by(tmdb_movie_id: id).review %></p>
                    <p class="btn-lg btn-warning"><%= @watcheds.find_by(tmdb_movie_id: id).rate %></p>
                </div>
            <% end %>
        </div>
        <div>
            <p class="h2">CHECK</p>
            <% @check_movie_ids.each do |id| %>
                <div class="inline">
                    <% movie_info = Movie.details(id) %>
                    <%= link_to image_tag("https://image.tmdb.org/t/p/w200#{movie_info["poster_path"]}", alt: "poster"), movie_path(id) %>
                    <p class="center"><%= link_to movie_info["title"], movie_path(id) %></p>
                    <div>
                        <% if @checks.find_by(tmdb_movie_id: id).prepare.blank?  %>
                            <p class="btn-lg btn-warning">CHECK!</p>
                        <% else %>
                            <p class="btn-lg btn-danger">PREPARATION!</p>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>