config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "homes#top"
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  get 'movies/search'
  resources :movies, only: [:show] do
    resource :watcheds, only: [:new, :create, :edit, :update, :destroy]
    resource :checks, only: [:create, :update, :destroy]
  end

  get 'genres/:id' => 'genres#show', as: 'genre'
  get 'people/:id' => 'people#show', as: 'person'

  

  namespace :admins do
    root to: "homes#top"
    get 'homes/about'
    resources :users, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  include ActiveModel::Model

	include HTTParty

  # default_options.update(verify: false) # disable SSL verification(必要に応じて)
  default_params api_key: ENV['TMDb_API_KEY'], language: 'en-US' #共通パラメタ
  format :json

  # キーワードによる検索機能
  # https://developers.themoviedb.org/3/search/search-keywordsを参照
  def self.search term
    base_uri 'https://api.themoviedb.org/3/search/movie'
    get("", query: { query: term }) # {}の中身はパラメタ
  end

  # 指定の映画の詳細情報を取得
  # https://developers.themoviedb.org/3/movies/get-movie-detailsを参照
  def self.details id
    base_uri "https://api.themoviedb.org/3/movie/#{id}"
    get("", query: { } ) #パラメタなし
  end

  # 指定のクレジットを取得
  # https://developers.themoviedb.org/3/movies/get-movie-creditsを参照
  def self.credits id
    base_uri "https://api.themoviedb.org/3/movie/#{id}/credits"
    get("", query: { } ) #パラメタなし
  end

  # 指定のクレジットの詳細情報を取得
  # https://developers.themoviedb.org/3/movies/get-credit-detailsを参照
  def self.credit_details id
    base_uri "https://api.themoviedb.org/3/credit/#{id}"
    get("", query: { } ) #パラメタなし
  end

  # 指定の映画の予告編を取得
  # https://developers.themoviedb.org/3/genres/get-movie-listを参照
  def self.videos id
    base_uri "https://api.themoviedb.org/3/movie/#{id}/videos"
    get("", query: { } ) #パラメタなし
  end

  # 指定の映画のジャンルを取得
  # https://developers.themoviedb.org/3/genres/get-movie-listを参照
  def self.genres
    base_uri "https://api.themoviedb.org/3/genre/movie/list"
    get("", query: { } ) #パラメタなし
  end

  # トレンドの映画一覧を取得
  # https://developers.themoviedb.org/3/trending/get-trendingを参照
  def self.trendings
    base_uri "https://api.themoviedb.org/3/trending/movie/week"
    get("", query: { } ) #パラメタなし
  end
end

app/models/person.rb
class Person < ApplicationRecord
	include ActiveModel::Model 
	include HTTParty

	# default_options.update(verify: false) # disable SSL verification(必要に応じて)
	default_params api_key: ENV['TMDb_API_KEY'], language: 'en-US' #共通パラメタ
	format :json

	# 指定のパーソンの詳細を取得
	# https://developers.themoviedb.org/3/people/get-person-detailsを参照
	def self.details id
		base_uri "https://api.themoviedb.org/3/person/#{id}"
		get("", query: { } ) #パラメタなし
	end

	# 指定のパーソンの映画作品全てを取得
	# https://developers.themoviedb.org/3/people/get-person-movie-creditsを参照
	def self.movie_credits id
		base_uri "https://api.themoviedb.org/3/person/#{id}/movie_credits"
		get("", query: { } ) #パラメタなし
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :watcheds
  has_many :checks
end

app/models/watched.rb
class Watched < ApplicationRecord
  belongs_to :user
  enum rate: {AllTimeBest: 0, LOVE: 1, LIKE: 2, OK: 3, DISLIKE: 4}
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @trend_movies = Movie.trendings["results"]
    @watcheds = current_user.watcheds
    @checks = current_user.checks
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  def show
    @user = User.find(params[:id])
    @watcheds = @user.watcheds
    @watched_movie_ids = []
    @watcheds.each do |watched|
      @watched_movie_ids << watched.tmdb_movie_id
    end
    @checks = @user.checks
    @check_movie_ids = []
    @checks.each do |check|
      @check_movie_ids << check.tmdb_movie_id
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
		if	@user.update(user_params)
			flash[:notice] = "successfully"
			redirect_to user_path(current_user.id)
		else
			flash[:notice] = "error"
			render :edit
		end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
  def correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watcheds_helper.rb
module WatchedsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinephilia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  </head>

  <body>
    <header>
      <div class="container center-block">
        <% if user_signed_in? %>
          <%= link_to image_tag("logo.jpg", size: '150x150'), root_path, class: "h4 nav-menu" %>
          <%= link_to "ABOUT", homes_about_path, class: "h4 nav-menu" %>
          <%= link_to "MY PAGE", user_path(current_user.id), class: "h4 nav-menu" %>
          <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "h4 nav-menu" %>
        <% elsif admin_signed_in? %>
          <%= link_to image_tag("logo.jpg", size: '150x150'), root_path, class: "h4 nav-menu" %>
          <%= link_to "TOP", admins_root_path, class: "h4 nav-menu" %>
          <%= link_to "ABOUT", admins_homes_about_path, class: "h4 nav-menu" %>
          <%= link_to "USERS", admins_users_path, class: "h4 nav-menu" %>
          <%= link_to "LOG OUT", destroy_admin_session_path, method: :delete, class: "h4 nav-menu" %>
        <% else %>
          <%= link_to image_tag("logo.jpg", size: '150x150'), root_path, class: "h4 nav-menu" %>
          <%= link_to "TOP", root_path, class: "h4 nav-menu" %>
          <%= link_to "ABOUT", homes_about_path, class: "h4 nav-menu" %>
          <%= link_to "SIGN UP", new_user_registration_path, class: "h4 nav-menu" %>
          <%= link_to "LOG IN", new_user_session_path, class: "h4 nav-menu" %>
        <% end %>
        <%= form_tag(movies_search_path, method: :get, class: "h4") do %>
          <%= search_field_tag :looking_for, nil, placeholder: 'Movie titles…' %>
          <%= submit_tag 'SEARCH' %>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>